import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = defineConfig([
  ...nextVitals,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    // Generated by `npm run test:coverage`; the HTML report bundles its own
    // vendored scripts, which aren't ours to lint.
    "coverage/**",
  ]),
]);

export default eslintConfig;
