import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = defineConfig([
  ...nextVitals,
  // The Next preset leaves this off. Without it, a name deleted in a refactor
  // but still used in a "use server" file (which Vitest cannot import) ships
  // as a runtime ReferenceError, as HEX_COLOR did on the Settings page.
  { rules: { "no-undef": "error" } },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    // Generated by `npm run test:coverage`; the HTML report bundles its own
    // vendored scripts, which aren't ours to lint.
    "coverage/**",
    // Generated by `npm run test:e2e`, for the same reason.
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
